version: "3.8"

services:

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  asynqmon:
    image: hibiken/asynqmon:0.7
    command:
      - "--redis-addr=redis:6379"
    ports:
      - "8081:8080"
