version: "3.8"

services:

  cockroach:
    container_name: temporal-cockroach
    hostname: cockroach
    image: cockroachdb/cockroach
    command:
      - start-single-node
      - --insecure
    cap_drop:
      - ALL
    networks:
      - temporal-network
    restart: on-failure
    security_opt:
      - no-new-privileges
    tty: false
    volumes:
      - /var/lib/cockroach

  elasticsearch:
    container_name: temporal-elasticsearch
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    networks:
      - temporal-network
    ports:
      - "9200:9200"
    volumes:
      - /var/lib/elasticsearch/data

  kibana:
    container_name: temporal-kibana
    image: kibana:8.7.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    depends_on:
      - cockroach
      - elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=26257
      - POSTGRES_USER=root
      - POSTGRES_PWD=
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    links:
      - cockroach:postgres
    networks:
      - temporal-network
    ports:
      - "7233:7233"
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
    ports:
      - "8070:8080"

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
